CONFIG_LOG=y
CONFIG_I2C=y    # Enable the i2c driver
#CONFIG_SENSOR=y # Not actually needed for this example
#CONFIG_BME280=y # Not actually needed for this example
CONFIG_CBPRINTF_FP_SUPPORT=y
#CONFIG_LOG_MODE_MINIMAL=y

# 1. Total byte allocation pool for deferred strings
CONFIG_LOG_BUFFER_SIZE=8192

# 2. Allocate distinct tracking blocks rather than a raw continuous ring
CONFIG_LOG_BLOCK_IN_THREAD=y
CONFIG_LOG_BLOCK_IN_THREAD_TIMEOUT_MS=500