CONFIG_GPIO=y
CONFIG_SERIAL=y         # usually enabled by default through the board’s devicetree

CONFIG_UART_CONSOLE=y
CONFIG_UART_0_INTERRUPT_DRIVEN=n # order of these matters??
CONFIG_UART_ASYNC_API=y # important to enable the asynchronous API of the serial driver
