#include <zephyr/kernel.h>     // for zephyr kernel
#include <zephyr/sys/printk.h> // kernel print function

#ifdef CONFIG_MYFUNCTION
#include "myfunction.h"
#endif

// NOTE
// prj.conf is left empty because the console drivers needed by printk() are enabled by default by the board configuration file. This is covered in-depth in Lesson 4.

// NOTE
// Default speed is set in devicetree file to 115200 baud

// To use the nrfConnect SDK built in terminal, go to connected devices section in extension panel, click the device drop down, and connect to VCOM with the plug icon. Select 115200 8n1 rtscts off

// NOTE
// The l3_e2 example assumes use of the NRF52840DK, which has an interface MCU (IMCU) which connects to the dev kit MCUs UART port
// In such cases, the IMCU acts as a USB to UART bridge, and the baud rate is set in the devicetree overlay file. The default speed is set to 115200 baud, but it can be changed to any value supported by the board's UART driver. The baud rate is the property current-speed in the nrf-uart binding, which is defined and specified in nrf-uart-common.yaml.
// However, for the promicro clone I have, USB CDC is forced by default via CONFIG_BOARD_REQUIRES_SERIAL_BACKEND_CDC_ACM=y
// in the .config file generated by the build. Not entirely sure which file this setting comes from, but good to know, since changing the UART0 baud rate has no effect.
// USBCDC simply emulates a virtual serial port over USB, and the baud rate is not relevant in this case. The baud rate setting is ignored by the USB CDC driver, and the host computer will use its own settings for the virtual serial port. The baud rate setting in the devicetree overlay file is only relevant for physical UART connections, not for USB CDC connections.

int main(void) {
	while (1) {
        #ifdef CONFIG_MYFUNCTION
            int a = 3, b = 4;
            printk("The sum of %d and %d is %d\n", a, b, sum(a, b));
        #else
            printk("MYFUNCTION not enabled\n");
        #endif
            k_msleep(1000);
    }
	return 0;
}