CONFIG_MULTITHREADING=y

# This configuration defaults to yes in all nRF Connect SDK applications and isnt strictly necessary to enable manually. 

CONFIG_PRINTK=y
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=10
CONFIG_TIMESLICE_PRIORITY=4

CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y