CONFIG_TIMESLICING=y

# the maximum time (in ms) that the current running thread has before it is forcefully preempted by the scheduler to allow the other equal priority threads to run.
CONFIG_TIMESLICE_SIZE=10 

# threads with higher priority than this threshold are not subject to time slicing. 
# This means priorities (0 to 15) will be affected by time-slicing only when two or more threads exist in one level. 
# It’s always important to remember that time slicing only affect threads with the same priority level.
CONFIG_TIMESLICE_PRIORITY=0